version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  minitest:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    environment:
      RAILS_ENV: "test"
      RACK_ENV: "test"
    steps:
      - checkout

      - run: bundle install

      # Static Code Analysis
      - run: bundle exec rubocop

      # Unit tests
      - run:
          shell: /bin/bash
          command: CI=true bundle exec rails test
