version: 2.1

workflows:
  version: 2
  commit:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node

    steps:
      - checkout

      - run: bundle

      # Static Code Analysis
      - run: rubocop

      # Unit tests
      - run:
          shell: /bin/bash
          command: CI=true bundle exec rails test
